layout_spectrum: 0.9253491
color:
  saturation: 0.7884637
  brandStrength: 0.6178959
  lightness: 0.5300752
  rhythmicContrast: 0.4581096
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
typography_spectrum: 1
name: Alexander Wang Photography
